source "https://rubygems.org"

gem "fastlane"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

# Added at 2018-04-24 10:18:44 +0200 by kosssi:
gem "cocoapods", "~> 1.4"
