#!/bin/bash

set -e

function check_dir {
  dir=$1
  if [[ ! -d $dir ]]; then
    echo "${dir} is not a directory :("
    echo "If your cozy passwords are not stored at the root of your password-store, you can maybe"
    echo "use the COZY_DIRECTORY env variable, for example (slash at the end) :"
    echo "env COZY_DIRECTORY='cozy/' ./scripts/import_mobile_keys"
    exit 1
  fi
}

function extract_from_keepass {
  src="$1"
  dest="$2"
  echo "Extracting from $1 to $2"
  pass show "${COZY_DIRECTORY}$1" > "$2"
}

function cp_from_keepass {
  local path="${PASSWORD_STORE_PATH}$1"
  echo "Copying from $path to $2"
  cp "$path" "$2"
}


COZY_DIRECTORY=${COZY_DIRECTORY:-""}
PASSWORD_STORE_PATH=${PASSWORD_STORE_PATH:-"$HOME/.password-store/${COZY_DIRECTORY}"}
BANKS_DIR_IN_PASSWORD_STORE=${PASSWORD_STORE_PATH}cozy-banks
check_dir $BANKS_DIR_IN_PASSWORD_STORE

mkdir -p src/targets/mobile/keys/{android,ios}
cp_from_keepass cozy-banks/keys/android/cozy-banks-release-key.jks ./src/targets/mobile/keys/android/cozy-banks-release-key.jks
cp_from_keepass cozy-banks/keys/android/key.json ./src/targets/mobile/keys/android/key.json
extract_from_keepass cozy-banks/keys/android/google-services.json ./src/targets/mobile/keys/android/google-services.json
extract_from_keepass cozy-banks/keys/ios/GoogleService-Info.plist ./src/targets/mobile/keys/ios/GoogleService-Info.plist
