#!/bin/bash

set -eu
cozyDomain=$1

if [[ $cozyDomain == "cozy.tools:8080" ]]; then
  cozy-stack instances token-app $cozyDomain banks
else
  tokenFile=$(make-token $cozyDomain $PERMISSIONS)
  cat $tokenFile | jq -r '.token'
fi
