platform :ios do
  desc "Deploy ios app on the appstore"

  lane :devices do
    register_devices(
       devices: {
         "Patrick iPhone 6s" => "dbb0aa403f6928368467d3f10b28a61336e52023",
         "Quentin iPhone X" => "f104c368769384e8f043ba497a74f704d27d6d3f"
       }
    )
  end

  lane :screenshots do
    appstore(
      skip_binary_upload: true,
      skip_metadata: true
    )
  end

  lane :deploy do
    match(
      shallow_clone: true,
      clone_branch_directly: true,
      type: "appstore",
      git_url: "git@gitlab.cozycloud.cc:labs/mobile-certificates.git",
      force: true
    )
    cordova(platform: 'ios', build_flag: ['-UseModernBuildSystem=0'])
    appstore(
      ipa: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'],
      skip_screenshots: true,
      skip_metadata: true
    )
  end
end

platform :android do
  desc "Deploy android app on play store"

  lane :screenshots do
    supply(
      skip_upload_apk: true,
      skip_upload_metadata: true,
      track: 'beta'
    )
  end

  lane :deploy do
    supply(
      apk: './build/android/cozy-banks.apk',
      track: 'beta',
      skip_upload_screenshots: true,
      skip_upload_images: true,
      skip_upload_metadata: true
    )
  end
end
