import get from 'lodash/get'
import includes from 'lodash/includes'

// To update this list used this command on banking konnector:
// $ cat src/publish/manifests.json | jq '[.[].slug]' | sort
const bankingSlug = [
  'afer',
  'ageas',
  'agipi',
  'allianzretraitecollective',
  'altaprofits',
  'americanexpress',
  'amundiee',
  'amunditc',
  'arkea',
  'assuranceviecom',
  'axabanque102',
  'axaer',
  'axaes',
  'banquecasino',
  'banquepopulaire',
  'banquepostaleee',
  'barclays136',
  'bcp',
  'becm',
  'bfcoi',
  'bforbank97',
  'bnpes',
  'bnpparibas82',
  'bolden',
  'boursorama83',
  'bpe',
  'bred',
  'breddispobank',
  'caatlantica3',
  'caels',
  'caissedepargne1',
  'carrefour159',
  'casden173',
  'ccso',
  'cdngroup109',
  'cdngroup88',
  'cetelem',
  'chalus',
  'cic45',
  'cic63',
  'cicee',
  'comptenickel168',
  'courtois',
  'creditcooperatif148',
  'creditdunordes',
  'creditfoncier',
  'creditmaritime',
  'creditmutueles',
  'edmondderothschild',
  'epargnissimo',
  'epsenses',
  'esalia',
  'fortuneo84',
  'gan',
  'generali',
  'groupama',
  'groupamaes',
  'hellobank145',
  'hsbc119',
  'ingdirect95',
  'kolb',
  'labanquepostale44',
  'laydernier',
  'lcl-linxo',
  'linxea',
  'maafvie',
  'macsf',
  'maif-nestor',
  'manymore',
  'mesplacementsfr',
  'monabanq96',
  'moneoresto',
  'mutavie',
  'n26',
  'natixis',
  'nuger',
  'oddo',
  'oney',
  'orangebank',
  'palatine',
  'paypal',
  'psa',
  'revolut',
  'rhonealpes',
  'sbe',
  'sharinbox',
  'societegenerale',
  'socram',
  'sofinco',
  'sogeretraite',
  'spirica',
  'swisslife',
  'swisslifebp',
  'tarneaud',
  'transatlantique',
  'transatlantiquees',
  'unionfinancieredefrance',
  'wesave',
  'yomoni',
  'zesto'
]

export const isBankTrigger = trigger =>
  includes(bankingSlug, get(trigger, 'message.konnector'))

export const isBankKonnector = job =>
  includes(bankingSlug, get(job, 'konnector'))
